// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace Feelknit.iOS
{
	public partial class RelatedFeelingsViewController : UIViewController
	{
		public RelatedFeelingsViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
